In [1]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials

# use creds to create a client to interact with the Google Drive API
scope = ['https://spreadsheets.google.com/feeds']
creds = ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope)
client = gspread.authorize(creds)
 
# Find a workbook by name and open the first sheet
# Make sure you use the right name here.
sheet = client.open("Xilinx_Hackathon_2017").sheet1

In [2]:
# Extract and print all of the values
all_faces_str = sheet.get_all_values()
print(all_faces_str)

[['Filler', '', '', ''], ['[[1,2,3],[4,5,6]]', '[[10,20,30],[40,50,60]]', '[[11,21,13],[41,51,61]]', '[[12,22,32],[42,52,62]]']]


In [3]:
data = all_faces_str[1:]
print (data)

[['[[1,2,3],[4,5,6]]', '[[10,20,30],[40,50,60]]', '[[11,21,13],[41,51,61]]', '[[12,22,32],[42,52,62]]']]


In [4]:
type (data)

list

In [6]:
realData = data[0]
print (realData)

['[[1,2,3],[4,5,6]]', '[[10,20,30],[40,50,60]]', '[[11,21,13],[41,51,61]]', '[[12,22,32],[42,52,62]]']


In [15]:
import numpy as np

firstElement = data[0][0]
firstList = np.array(eval(firstElement))
print (type(firstList))
print (firstList)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [26]:




myTotal = np.array([])
for element in data[0]:
   myArray = np.array(eval(element))
   #print (myArray)
   myTotal = np.vstack([myTotal,myArray]) if myTotal.size else myArray
   

print (myTotal)
    
    


[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]
 [11 21 13]
 [41 51 61]
 [12 22 32]
 [42 52 62]]
